[options]
; ---- Cấu hình Database ----
db_host = db
db_port = 5432
db_user = evddn
db_password = evddn@123!@#$%
db_name = evddn
db_maxconn = 64

lang = vi_VI
timezone = Asia/Ho_Chi_Minh

; ---- Đường dẫn Addons ----
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

; ---- Cấu hình chung ----
admin_passwd = admin

; ---- Tối ưu cho production ----
workers = 4

max_cron_threads = 2

list_db = False


proxy_mode = True

; ---- Đồng bộ Timeout với Nginx (Chống đứt gãy khi xử lý dữ liệu nặng) ----
limit_time_cpu = 3600
limit_time_real = 3600

; ---- Giới hạn RAM (Chống sập máy chủ - Cấu hình an toàn khoảng 2GB/Worker) ----
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560





