# cho phep kêt noi het
#host    all     evddn    0.0.0.0/0    md5

# Cho phép user evddn từ mạng Docker (172.18.0.0/16) kết nối không cần SSL
host    all     evddn    172.18.0.0/16    md5


# Cho phép user evddn kết nối từ IPv4 localhost
host    all     evddn    127.0.0.1/32    md5

# Cho phép user evddn kết nối từ IPv6 localhost (::1)
host    all     evddn    ::1/128         md5


# Từ chối tất cả các kết nối khác
host    all      all      0.0.0.0/0    reject
