[options]
; ---- Cấu hình Database ----
db_host = 192.168.1.98
db_port = 5432
db_user = erp
db_password = ERP@123!@#
db_name = erp
db_maxconn = 64

lang = vi_VI
timezone = Asia/Ho_Chi_Minh

; ---- Đường dẫn Addons ----
/opt/odoo/addons
#addons_path =/mnt/extra-addons/odoo/addons,/mnt/extra-addons/custom_addons_p,/mnt/extra-addons/custom_addons_f,/mnt/extra-addons/custom_addons_fs
data_dir = /var/lib/odoo

; ---- Cấu hình chung ----
admin_passwd = admin


; ---- Tối ưu cho production ----
workers = 4
max_cron_threads = 2
#workers = 0
#max_cron_threads = 1

list_db = False

limit_time_cpu = 3600
limit_time_real = 3600

server_wide_modules = base,web
proxy_mode = False





