[options]
; ---- Cấu hình Database ----
db_host = db
db_port = 5432
db_user = erp
db_password = ERP@123!@#
db_name = erp
db_maxconn = 64

lang = vi_VI
timezone = Asia/Ho_Chi_Minh

; ---- Đường dẫn Addons ----
addons_path =/mnt/extra-addons/odoo/addons,/mnt/extra-addons/nhamay,/mnt/extra-addons/custom_addons_p,/mnt/extra-addons/custom_addons_f,/mnt/extra-addons/custom_addons_fs
data_dir = /var/lib/odoo

; ---- Cáº¥u hÃ¬nh chung ----
admin_passwd = admin


; ---- Tá»‘i Æ°u cho production ----
list_db = True
server_wide_modules = base,web,bus
jwt_extra_key = FS@2025
auto_url = /api


proxy_mode = True

longpolling_port = 8072

workers = 4
max_cron_threads = 2

limit_time_real = 600
limit_time_cpu = 300
limit_request = 8192



