[options]
; ---- Cấu hình Database ----
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = vddn
db_maxconn = 64

; ---- Đường dẫn Addons ----
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

; ---- Cấu hình chung ----
admin_passwd = admin

; ---- Tối ưu cho production ----
workers = 4

max_cron_threads = 2

list_db = False

limit_time_real = 120
# Disable Content-Security-Policy
csp = False

proxy_mode = False




