worker_processes auto;
events { worker_connections 1024; }

http {
     ## Tăng giới hạn header/URL
    client_header_buffer_size 16k;
    large_client_header_buffers 4 32k;
    ## Gzip config
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/xml
        application/xml+rss
        application/json
        application/ld+json
        image/svg+xml
        font/woff
        font/woff2
        application/font-woff
        application/font-woff2;


    ## Upstreams
    upstream odoo {
        server odoo:8069;
    }
    upstream odoochat {
        server odoo:8072;
    }

    # HTTP → HTTPS
    server {
        listen 80;
        server_name 192.168.1.230;
        return 301 https://$host$request_uri;
    }

    # HTTPS chính
    server {
        #listen 443 ssl http2;
        listen 443 ssl;
        http2 on;
        server_name 192.168.1.230;

        ssl_certificate     /etc/nginx/ssl/erp.crt;
        ssl_certificate_key /etc/nginx/ssl/erp.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        proxy_read_timeout  3600;
        proxy_connect_timeout 3600;
        proxy_send_timeout 3600;
        client_max_body_size 200M;


        location / {
          proxy_pass http://odoo;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }

        location /websocket {
          proxy_pass http://odoochat;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }

         location /longpolling{
          proxy_pass http://odoochat;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }


    }
}
