[options]
; ---- Cấu hình Database ----
db_host = db
db_port = 5432
db_user = erp
db_password = ERP@123!@#
db_name = erp
db_maxconn = 64

lang = vi_VI
timezone = Asia/Ho_Chi_Minh

; ---- Đường dẫn Addons ----
addons_path =/mnt/extra-addons/odoo/addons,/mnt/extra-addons/nhamay,/mnt/extra-addons/custom_addons_p,/mnt/extra-addons/custom_addons_f,/mnt/extra-addons/custom_addons_fs
data_dir = /var/lib/odoo

; ---- Cấu hình chung ----
admin_passwd = admin


; ---- Tối ưu cho production ----
proxy_mode = True
workers = 2
max_cron_threads = 1
longpolling_port = 8072

list_db = True

limit_time_cpu = 3600
limit_time_real = 3600

server_wide_modules = base,web,bus


jwt_extra_key = FS@2025
auto_url = /api







