version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: Nextcloud@123
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud"]
      interval: 10s
      retries: 10
    restart: always

  app:
    image: nextcloud:28-fpm
    container_name: nextcloud-app
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: Nextcloud@123
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin123
      NEXTCLOUD_TRUSTED_DOMAINS: 192.168.1.216
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.27
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx_logs:/var/log/nginx
      - ./nextcloud:/var/www/html:ro
    environment:
      TZ: Asia/Ho_Chi_Minh
    restart: always

volumes:
  db_data:
  nextcloud:
